### ISSUE TITLE
Metrics dashboard not working

### ISSUE THREAD

**Issue by GoHod** [peterkwells/uk-government-cats#28]
The page (https://peterkwells.github.io/uk-govt-cat-dashboard/) shows as blank on Mac OS Safari (latest versions).

**Comment by peterkwells** [comment]
Hmmm.... It's working OK here with the same setup - Safari Version 10.1 (12603.1.30.0.34)). It relies on a Heroku instance starting up so can take a little while to load if it's not up and running at the time someone looks, it took about 5secs for me.

Can you check again?

**Comment by GoHod** [comment]
Hi, yes, it's working now!
